-- 산술연산자

SELECT ENAME, SAL, SAL * 1.1
FROM T_EMP ;

SELECT ENAME, SAL, COMM , SAL + COMM -- null 값과의 산술연산은 무조건 null
FROM T_EMP ;

-- where 조건절

SELECT * FROM T_EMP WHERE JOB ='SALESMAN';
SELECT * FROM T_EMP WHERE JOB ='SALESman'; -- 문자열은 대소문자 구분

SELECT ENAME, SAL , DEPTNO FROM T_EMP WHERE DEPTNO = 10;

SELECT ename, sal FROM T_EMP WHERE sal > 2000;

SELECT ENAME , EMPNO , SAL FROM T_EMP WHERE ENAME = 'SCOTT';

SELECT NAME , GRADE FROM T_STUDENT WHERE GRADE BETWEEN 2 AND 3;
SELECT NAME , GRADE FROM T_STUDENT WHERE GRADE = 2 OR GRADE = 3;
SELECT NAME , GRADE FROM T_STUDENT WHERE GRADE IN (2, 3);
SELECT NAME , GRADE FROM T_STUDENT WHERE GRADE > 1 AND GRADE < 4;
SELECT NAME , GRADE FROM T_STUDENT WHERE GRADE NOT IN (1, 4);

SELECT NAME , PAY , "POSITION" FROM T_PROFESSOR WHERE PAY > 300 AND "POSITION" = '정교수';

SELECT NAME ,"POSITION" FROM T_PROFESSOR WHERE BONUS IS NULL ; -------- 미제

SELECT NAME FROM T_PROFESSOR WHERE NAME LIKE '김%';

SELECT ENAME FROM T_EMP WHERE ENAME LIKE '%NE%';

SELECT ENAME FROM T_EMP WHERE ENAME LIKE '_A%'; -- _무조건 하나 와야함

-------------------------------------order by
SELECT ENAME FROM T_EMP WHERE ENAME LIKE '%L%' ORDER BY ename DESC;

SELECT ENAME , JOB , SAL FROM T_EMP ORDER BY JOB DESC , SAL ASC ;

SELECT NAME , GRADE , HEIGHT FROM T_STUDENT ORDER BY GRADE ASC , HEIGHT DESC ;

