SELECT * FROM T_EMP ;

SELECT ENAME
FROM T_EMP
WHERE SAL > (SELECT SAL FROM T_EMP WHERE ENAME = 'SCOTT');

-- #7102
SELECT NAME, HEIGHT FROM T_STUDENT 
WHERE HEIGHT = (SELECT MAX(HEIGHT) FROM T_STUDENT);

-- #7103
SELECT s.NAME "학생이름", d.DNAME "1전공" FROM T_STUDENT s, T_DEPARTMENT d
WHERE s.DEPTNO1 = d.DEPTNO AND s.DEPTNO1 = (SELECT DEPTNO1 FROM T_STUDENT WHERE NAME = '이윤나');


-- #7104
SELECT p.NAME 교수명, TO_CHAR(p.HIREDATE, 'rrrr-mm-dd') 입사일, d.DNAME 학과명 FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE p.HIREDATE < (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '송도권');

-- #7105
SELECT NAME 이름, WEIGHT 몸무게 FROM T_STUDENT 
WHERE WEIGHT > (SELECT AVG(WEIGHT) FROM T_STUDENT);

-- #7106
SELECT NAME 이름, PAY 급여, TO_CHAR(HIREDATE, 'rr/mm/dd') 입사일 FROM T_PROFESSOR
WHERE HIREDATE = (SELECT HIREDATE FROM T_PROFESSOR WHERE NAME = '심슨') AND PAY < (SELECT PAY FROM T_PROFESSOR WHERE NAME = '조인형'); 

-- #7107
SELECT EMPNO, NAME, DEPTNO FROM T_EMP2 e
WHERE DEPTNO IN (SELECT DCODE FROM T_DEPT2 WHERE AREA = '서울지사');

-- #7108
SELECT NAME 이름, POST 직급, TO_CHAR(PAY, '999,999,999') || '원' 연봉 FROM T_EMP2 
WHERE PAY > (SELECT MIN(PAY) FROM T_EMP2 WHERE POST = '과장')
ORDER BY PAY DESC;

SELECT NAME 이름, POST 직급, TO_CHAR(PAY, '999,999,999') || '원' 연봉 FROM T_EMP2 
WHERE PAY >ANY (SELECT PAY FROM T_EMP2 WHERE POST = '과장');

-- #7109
SELECT NAME 이름, GRADE 학년, WEIGHT 몸무게 FROM T_STUDENT 
WHERE WEIGHT <ALL (SELECT WEIGHT FROM T_STUDENT WHERE GRADE = 4);













