-- #7201
SELECT GRADE 학년, NAME 이름, HEIGHT 키 FROM T_STUDENT 
WHERE (GRADE, HEIGHT) IN (SELECT GRADE, MAX(HEIGHT) FROM T_STUDENT GROUP BY GRADE)
ORDER BY GRADE ASC;

-- #7202
SELECT p.PROFNO "교수번호", p.NAME "교수명", TO_CHAR(p.HIREDATE, 'rrrr-mm-dd') "입사일", d.DNAME "학과명" FROM T_PROFESSOR p, T_DEPARTMENT d
WHERE (d.DEPTNO, p.HIREDATE) IN (SELECT d.DEPTNO, MIN(p.HIREDATE) FROM T_PROFESSOR p, T_DEPARTMENT d WHERE p.DEPTNO = d.DEPTNO GROUP BY d.DEPTNO);

-- #7203
SELECT NAME 사원명, POST 직급, PAY 연봉 FROM T_EMP2 
WHERE (POST, PAY) IN (SELECT POST, MAX(PAY) FROM T_EMP2 GROUP BY POST)
ORDER BY PAY ASC;

-- #7204
SELECT d.DNAME 부서명, e.NAME 직원명, e.PAY 연봉 FROM T_EMP2 e, T_DEPT2 d
WHERE e.DEPTNO = d.DCODE AND e.PAY <ALL (SELECT AVG(e.PAY) FROM T_EMP2 e, T_DEPT2 d GROUP BY e.DEPTNO)
ORDER BY e.PAY ASC;

-- #7205
SELECT NAME 사원이름, POST 직급, PAY 급여 FROM T_EMP2 a
WHERE PAY >= (SELECT AVG(PAY) FROM T_EMP2 b WHERE NVL(a.POST, ' ') = NVL(b.POST, ' '));

-- #7206
SELECT e.NAME "사원이름", (SELECT d.DNAME FROM T_DEPT2 d WHERE d.DCODE = e.DEPTNO)"부서이름" FROM T_EMP2 e;













