-- INITCAP() 함수
-- #4101
SELECT INITCAP('pretty girl') 
FROM dual;

-- #4102
SELECT INITCAP(ID) ID FROM T_STUDENT WHERE DEPTNO1 = 201;

-- LOWER(), UPPER()
-- #4103
SELECT NAME, ID, LOWER(ID) 소문자, upper(ID) 대문자 FROM T_STUDENT WHERE DEPTNO1 = 201;

-- LENGTH / LENGTHB
-- #4104
SELECT NAME 이름, ID, LENGTH(id) 글자수 FROM T_STUDENT WHERE LENGTH(ID) >= 9;

-- #4105
SELECT NAME 이름, LENGTH(NAME) 길이, LENGTHB(NAME) 바이트 FROM T_STUDENT WHERE DEPTNO1 = 201;

-- CONCAT() 함수
-- #4106
SELECT CONCAT(NAME, POSITION) 교수님명단 FROM T_PROFESSOR WHERE DEPTNO = 101;

-- SUBSTR() 함수
SELECT SUBSTR('ABCDE', 2, 3) FROM dual;
SELECT SUBSTR('ABCDE', 20, 3) FROM dual;
SELECT SUBSTR('ABCDE', -2, 3) FROM dual;


-- #4107
SELECT NAME, SUBSTR(JUMIN, 1, 6) 생년월일 FROM T_STUDENT WHERE DEPTNO1 = 101;

-- #4108
SELECT NAME, SUBSTR(JUMIN, 1, 6) 생년월일 FROM T_STUDENT WHERE SUBSTR(JUMIN, 3, 2) = '08';
SELECT NAME, SUBSTR(JUMIN, 1, 6) 생년월일 FROM T_STUDENT WHERE JUMIN LIKE '__08%';

-- #4109
SELECT NAME, JUMIN FROM T_STUDENT WHERE GRADE = 4 AND SUBSTR(JUMIN, 7, 1) = '2';

SELECT INSTR('a*b*c*', '*', 1, 1) FROM dual; -- 2
SELECT INSTR('a*b*c*', '*', 1, 2) FROM dual; -- 4
SELECT INSTR('a*b*c*', '*', 3, 2) FROM dual; -- 6
SELECT INSTR('a*b*c*', '*', -4, 1) FROM dual; -- 2
SELECT INSTR('a*b*c*', '*', -4, 2) FROM dual; -- 0
SELECT INSTR('a*b*c*', '*', -2, 2) FROM dual; -- 2

-- #4110
SELECT NAME, TEL, INSTR(TEL, ')', 1, 1) 위치 FROM T_STUDENT WHERE DEPTNO1 = 101;

-- #4111

SELECT NAME, TEL, SUBSTR(TEL, 1, INSTR(TEL,')') - 1) 지역번호 FROM T_STUDENT WHERE DEPTNO1 = 101;

-- LTRIM(), RTRIM(), TRIM()
SELECT LTRIM('슈퍼슈퍼슈가맨', '슈퍼') LTRIM,
LTRIM('슈퍼슈퍼슈가맨', '슈') LTRIM,
LTRIM('   슈퍼슈가맨') LTRIM,   -- defalut로 공백제거
RTRIM('우측공백제거     ') RTRIM,
TRIM('         슈퍼맨            ') TRIM, 
LTRIM('**********10000','*') 
FROM dual;

-- #4117
SELECT RTRIM(DNAME,'부') FROM T_DEPT2;

-- REPLACE 함수
SELECT REPLACE('슈퍼맨 슈퍼걸', '슈퍼', '파워') FROM dual;
SELECT REPLACE('아버지가 방에 들어간다', ' ', '') FROM dual;

-- #4118
SELECT REPLACE(NAME, SUBSTR(NAME, 1, 1),'#') 학생 FROM T_STUDENT WHERE DEPTNO1 = 102;

-- #4119
SELECT REPLACE(NAME, SUBSTR(NAME, 2, 1), '#') 학생 FROM T_STUDENT WHERE DEPTNO1 = 101;

-- #4120
SELECT NAME, REPLACE(JUMIN, SUBSTR(JUMIN, 7), '*******') 주민번호 FROM T_STUDENT WHERE DEPTNO1 = 101;

-- #4121
SELECT NAME, TEL, REPLACE(TEL, SUBSTR(TEL, INSTR(TEL, ')') + 1, 3), '###')전화번호
FROM T_STUDENT WHERE DEPTNO1 = 102;










